config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = 'lightningcat.herokuapp.com'
  get 'welcome/readme', as: :readme

  root 'home#index'

  resources :categories do
    resources :posts
  end

  resources :posts do
    get 'archive', on: :collection
    get 'list_my', on: :collection
    resources :comments
  end

  devise_for :users
end

app/views/layouts/_search.html.erb
<%= form_tag posts_path, :method => :get do %>
    <div class="row">
      <div class="large-12 columns">
        <div class="row collapse">
          <div class="small-10 columns">
            <%= text_field_tag :search, params[:search], placeholder: "search" %>
          </div>
          <div class="small-2 columns">
            <%= button_tag icon_button('magnifying-glass'), class: "button secondary postfix" %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title><%= content_for?(:title) ? yield(:title) : "Lightning Cat" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="title-bar" data-responsive-toggle="foundblog-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="foundblog-menu">
  <div class="top-bar-left">
    <ul class="menu">
      <li class="menu-text">Lightning<i>Cat</i>
      </li>
      <li>
        <a href="/">HOME</a>
      </li>
      <li><%= link_to "PostList", '/posts' %></li>
      <li><%= link_to "Archives", archive_posts_path %></li>
      <li><%= link_to "Readme", readme_path %></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="dropdown menu" data-dropdown-menu>
      <% if user_signed_in? %>
          <li>
            <a href="#"><%= current_user.email %></a>
            <ul class="menu">
              <li><%= link_to "My Profile", edit_user_registration_path %></li>
              <li><%= link_to "Roles : " + user_roles(current_user), '#' %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %></li>
            </ul>
          </li>
      <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</div>

<% if @check %>
  <div id="blog-banner">
    <%= image_tag 'blog_header.png', class: 'lightning-cat',width: '100%', height: 'auto' %>
  </div>
<% else %>
  <%= content_for?(:devise) ? yield(:devise) : yield(:general) %>
  <div class='row column'>
    <div id='footer'>
      <p>Copyright&reg; 2016, LightningCat, L3opold7, All rights reserved.</p>
    </div>
  </div>
<% end %>
</body>
</html>

app/views/layouts/devise_layout.html.erb
<!-- Section for Devise layouts -->
<%= content_for :devise do %>
    <div class='row'>
      <div class='medium-6 columns medium-centered'>
        <%= render partial: "shared/flash_messages", flash: flash %>
        <div style='margin:2em 0 5em;'>
          <%= yield %>
        </div>
      </div>
    </div>
<% end %>

<!-- Section for Applictiona Layout -->
<%= render template: 'layouts/application' %>

app/views/layouts/general_layout.html.erb
<!-- Section for General layouts -->
<% @recent_posts = Post.recent %>

<%= content_for :general do %>
    <div class='row'>
      <div class='large-9 medium-9 columns'>
        <div class='row'>
          <div class='medium-12 columns'>
            <%= render partial: "shared/flash_messages", flash: flash %>
            <%= yield %>
          </div>
        </div>
      </div>
      <div class='medium-3 columns' style="margin-top: 1em">

        <!-- 검색 -->
        <%= render "layouts/search" %>

        <div class='row'>
          <div class='medium-12 columns'>
            <!-- 내가 작성한 글목록 -->
            <% if user_signed_in? %>
                <p><%= link_to "My Posts <small>( #{Post.myposts(current_user).size} )</small>".html_safe, list_my_posts_path %></p>
            <% end %>

            <!-- 최근 글목록 -->
            <p>Recent Posts :</p>
            <ul>
              <% @recent_posts.each do | post | %>
                  <li><%= link_to truncate(post.title, length: 16), post_path(post) %></li>
              <% end %>
            </ul>

            <!-- 카테고리 분류 -->
            <p>Category : <small><%= link_to "Admin", categories_path if user_signed_in? && current_user.has_role?(:admin) %></small></p>
            <ul>
              <li>
                <%= link_to 'Uncategoried', posts_path(category_id: 0) %>
                <small><%= Post.uncategorized_posts.size %></small>
              </li>
              <% Category.all.each do | category | %>
                  <li>
                    <%= link_to category.name, category_posts_path(category) %>
                    <small><%= category.posts.published_posts.size %></small>
                  </li>
              <% end %>
            </ul>
            <!-- 태그 클라우드 -->
            <p>Tag Cloud :</p>
              <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
                <%= link_to tag.name, posts_path(tag: tag.name), :class => css_class %>
              <% end %>
            <hr>
            <center>
              <% if user_signed_in? %>
                  <%= link_to 'New Post', new_post_path, class: 'button small' %>
              <% else %>
                  <%= link_to 'Sign in', new_user_session_path, class: 'button small' %>
              <% end %>
            </center>
          </div>
        </div>
      </div>
    </div>
<% end %>

<%= render template: 'layouts/application' %>